language: java
dist: trusty
script: ./gradlew build

env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx1g"
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

notifications:
  slack: reportportal:fl6xWHVQp1jvsMmCJxYW9YKP